-- Price-only update for Ghana, Turkiye, Senegal, Uzbekistan, Jordan and Egypt.
-- Prices are clamped by position: GK 4.0-6.0, DEF 4.0-6.5, MID 4.5-10.5, FWD 4.5-12.0.
BEGIN;
UPDATE "Player" SET "price" = 4.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'EG' LIMIT 1) AND "name" = 'Ель Махді Сулейман';
UPDATE "Player" SET "price" = 4.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'EG' LIMIT 1) AND "name" = 'Мостафа Шобеїр';
UPDATE "Player" SET "price" = 4.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'EG' LIMIT 1) AND "name" = 'Мохамед Алаа';
UPDATE "Player" SET "price" = 5.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'EG' LIMIT 1) AND "name" = 'Мохамед Ель Шенаві';
UPDATE "Player" SET "price" = 4.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'EG' LIMIT 1) AND "name" = 'Ахмед Абу Ель Фотух';
UPDATE "Player" SET "price" = 4.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'EG' LIMIT 1) AND "name" = 'Карім Хафез';
UPDATE "Player" SET "price" = 6.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'EG' LIMIT 1) AND "name" = 'Мохамед Абдельмонем';
UPDATE "Player" SET "price" = 5.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'EG' LIMIT 1) AND "name" = 'Мохамед Хані';
UPDATE "Player" SET "price" = 4.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'EG' LIMIT 1) AND "name" = 'Рамі Рабіа';
UPDATE "Player" SET "price" = 4.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'EG' LIMIT 1) AND "name" = 'Тарек Алаа';
UPDATE "Player" SET "price" = 5.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'EG' LIMIT 1) AND "name" = 'Хоссам Абдельмагід';
UPDATE "Player" SET "price" = 4.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'EG' LIMIT 1) AND "name" = 'Яссер Ібрагім';
UPDATE "Player" SET "price" = 6.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'EG' LIMIT 1) AND "name" = 'Імам Ашур';
UPDATE "Player" SET "price" = 6.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'EG' LIMIT 1) AND "name" = 'Марван Аттія';
UPDATE "Player" SET "price" = 4.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'EG' LIMIT 1) AND "name" = 'Махмуд Сабер';
UPDATE "Player" SET "price" = 5.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'EG' LIMIT 1) AND "name" = 'Мостафа Зіко';
UPDATE "Player" SET "price" = 5.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'EG' LIMIT 1) AND "name" = 'Моханад Лашін';
UPDATE "Player" SET "price" = 4.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'EG' LIMIT 1) AND "name" = 'Набіль Емад';
UPDATE "Player" SET "price" = 5.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'EG' LIMIT 1) AND "name" = 'Хамді Фаті';
UPDATE "Player" SET "price" = 6.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'EG' LIMIT 1) AND "name" = 'Зізо';
UPDATE "Player" SET "price" = 5.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'EG' LIMIT 1) AND "name" = 'Ібрагім Адель';
UPDATE "Player" SET "price" = 10.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'EG' LIMIT 1) AND "name" = 'Мохамед Салах';
UPDATE "Player" SET "price" = 10.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'EG' LIMIT 1) AND "name" = 'Омар Мармуш';
UPDATE "Player" SET "price" = 7.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'EG' LIMIT 1) AND "name" = 'Трезеге';
UPDATE "Player" SET "price" = 6.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'EG' LIMIT 1) AND "name" = 'Хайссем Хассан';
UPDATE "Player" SET "price" = 5.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'EG' LIMIT 1) AND "name" = 'Хамза Абделькарім';
UPDATE "Player" SET "price" = 4.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'GH' LIMIT 1) AND "name" = 'Бенджамін Асаре';
UPDATE "Player" SET "price" = 4.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'GH' LIMIT 1) AND "name" = 'Джозеф Ананг';
UPDATE "Player" SET "price" = 4.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'GH' LIMIT 1) AND "name" = 'Лоуренс Аті-Зігі';
UPDATE "Player" SET "price" = 5.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'GH' LIMIT 1) AND "name" = 'Абдул Мумін';
UPDATE "Player" SET "price" = 4.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'GH' LIMIT 1) AND "name" = 'Абдул Рахман Баба';
UPDATE "Player" SET "price" = 5.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'GH' LIMIT 1) AND "name" = 'Аліду Сейду';
UPDATE "Player" SET "price" = 5.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'GH' LIMIT 1) AND "name" = 'Гідеон Менса';
UPDATE "Player" SET "price" = 4.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'GH' LIMIT 1) AND "name" = 'Деррік Луккассен';
UPDATE "Player" SET "price" = 5.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'GH' LIMIT 1) AND "name" = 'Джером Опоку';
UPDATE "Player" SET "price" = 5.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'GH' LIMIT 1) AND "name" = 'Йонас Аджетей';
UPDATE "Player" SET "price" = 6.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'GH' LIMIT 1) AND "name" = 'Коджо Пепра Оппонг';
UPDATE "Player" SET "price" = 4.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'GH' LIMIT 1) AND "name" = 'Марвен Сеная';
UPDATE "Player" SET "price" = 8.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'GH' LIMIT 1) AND "name" = 'Абдул Фатаву';
UPDATE "Player" SET "price" = 5.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'GH' LIMIT 1) AND "name" = 'Еліша Овусу';
UPDATE "Player" SET "price" = 6.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'GH' LIMIT 1) AND "name" = 'Калеб Іренкі';
UPDATE "Player" SET "price" = 4.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'GH' LIMIT 1) AND "name" = 'Квасі Сібо';
UPDATE "Player" SET "price" = 5.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'GH' LIMIT 1) AND "name" = 'Огюстін Боак''є';
UPDATE "Player" SET "price" = 6.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'GH' LIMIT 1) AND "name" = 'Томас Парті';
UPDATE "Player" SET "price" = 10.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'GH' LIMIT 1) AND "name" = 'Антуан Семеньйо';
UPDATE "Player" SET "price" = 7.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'GH' LIMIT 1) AND "name" = 'Брендон Томас-Асанте';
UPDATE "Player" SET "price" = 6.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'GH' LIMIT 1) AND "name" = 'Джордан Айю';
UPDATE "Player" SET "price" = 7.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'GH' LIMIT 1) AND "name" = 'Ернест Нуама';
UPDATE "Player" SET "price" = 7.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'GH' LIMIT 1) AND "name" = 'Іньякі Вільямс';
UPDATE "Player" SET "price" = 7.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'GH' LIMIT 1) AND "name" = 'Камалдін Сулемана';
UPDATE "Player" SET "price" = 7.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'GH' LIMIT 1) AND "name" = 'Крістофер Бонсу Баа';
UPDATE "Player" SET "price" = 5.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'GH' LIMIT 1) AND "name" = 'Прінс Квабена Аду';
UPDATE "Player" SET "price" = 4.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'JO' LIMIT 1) AND "name" = 'Абдалла Аль-Фахурі';
UPDATE "Player" SET "price" = 4.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'JO' LIMIT 1) AND "name" = 'Нур Бані Аттія';
UPDATE "Player" SET "price" = 4.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'JO' LIMIT 1) AND "name" = 'Язід Абулайла';
UPDATE "Player" SET "price" = 4.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'JO' LIMIT 1) AND "name" = 'Абдалла Насіб';
UPDATE "Player" SET "price" = 4.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'JO' LIMIT 1) AND "name" = 'Анас Бадаві';
UPDATE "Player" SET "price" = 4.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'JO' LIMIT 1) AND "name" = 'Іхсан Хаддад';
UPDATE "Player" SET "price" = 4.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'JO' LIMIT 1) AND "name" = 'Мо Абуалнаді';
UPDATE "Player" SET "price" = 4.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'JO' LIMIT 1) AND "name" = 'Мохаммад Абу Хашиш';
UPDATE "Player" SET "price" = 4.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'JO' LIMIT 1) AND "name" = 'Саед Аль-Росан';
UPDATE "Player" SET "price" = 4.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'JO' LIMIT 1) AND "name" = 'Салім Обайд';
UPDATE "Player" SET "price" = 4.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'JO' LIMIT 1) AND "name" = 'Хусам Абу Дахаб';
UPDATE "Player" SET "price" = 4.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'JO' LIMIT 1) AND "name" = 'Язан Аль-Араб';
UPDATE "Player" SET "price" = 4.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'JO' LIMIT 1) AND "name" = 'Амер Джамус';
UPDATE "Player" SET "price" = 4.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'JO' LIMIT 1) AND "name" = 'Ібрагім Садех';
UPDATE "Player" SET "price" = 4.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'JO' LIMIT 1) AND "name" = 'Мохаммад Аль-Дауад';
UPDATE "Player" SET "price" = 4.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'JO' LIMIT 1) AND "name" = 'Моханнад Абу Таха';
UPDATE "Player" SET "price" = 4.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'JO' LIMIT 1) AND "name" = 'Нізар Аль-Рашдан';
UPDATE "Player" SET "price" = 4.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'JO' LIMIT 1) AND "name" = 'Нур Аль-Равабдех';
UPDATE "Player" SET "price" = 4.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'JO' LIMIT 1) AND "name" = 'Раджаї Айед';
UPDATE "Player" SET "price" = 4.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'JO' LIMIT 1) AND "name" = 'Алі Азайзе';
UPDATE "Player" SET "price" = 5.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'JO' LIMIT 1) AND "name" = 'Алі Олван';
UPDATE "Player" SET "price" = 5.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'JO' LIMIT 1) AND "name" = 'Ібрагім Сабра';
UPDATE "Player" SET "price" = 4.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'JO' LIMIT 1) AND "name" = 'Махмуд Аль-Марді';
UPDATE "Player" SET "price" = 5.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'JO' LIMIT 1) AND "name" = 'Мохаммад Абу Зрайк';
UPDATE "Player" SET "price" = 7.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'JO' LIMIT 1) AND "name" = 'Муса Аль-Таамарі';
UPDATE "Player" SET "price" = 4.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'JO' LIMIT 1) AND "name" = 'Одех Аль-Фахурі';
UPDATE "Player" SET "price" = 5.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'SN' LIMIT 1) AND "name" = 'Еванн Діуф';
UPDATE "Player" SET "price" = 5.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'SN' LIMIT 1) AND "name" = 'Едуар Менді';
UPDATE "Player" SET "price" = 4.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'SN' LIMIT 1) AND "name" = 'Морі Діау';
UPDATE "Player" SET "price" = 4.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'SN' LIMIT 1) AND "name" = 'Абдулає Сек';
UPDATE "Player" SET "price" = 5.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'SN' LIMIT 1) AND "name" = 'Антуан Менді';
UPDATE "Player" SET "price" = 6.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'SN' LIMIT 1) AND "name" = 'Ель Хаджі Малік Діуф';
UPDATE "Player" SET "price" = 5.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'SN' LIMIT 1) AND "name" = 'Ісмаїл Якобс';
UPDATE "Player" SET "price" = 6.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'SN' LIMIT 1) AND "name" = 'Калідо Кулібалі';
UPDATE "Player" SET "price" = 6.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'SN' LIMIT 1) AND "name" = 'Крепен Діатта';
UPDATE "Player" SET "price" = 6.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'SN' LIMIT 1) AND "name" = 'Мамаду Сарр';
UPDATE "Player" SET "price" = 6.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'SN' LIMIT 1) AND "name" = 'Мусса Ніакате';
UPDATE "Player" SET "price" = 4.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'SN' LIMIT 1) AND "name" = 'Бара Сапоко Ндіає';
UPDATE "Player" SET "price" = 5.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'SN' LIMIT 1) AND "name" = 'Ідрісса Гує';
UPDATE "Player" SET "price" = 8.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'SN' LIMIT 1) AND "name" = 'Ламін Камара';
UPDATE "Player" SET "price" = 7.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'SN' LIMIT 1) AND "name" = 'Пап Гує';
UPDATE "Player" SET "price" = 8.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'SN' LIMIT 1) AND "name" = 'Пап Матар Сарр';
UPDATE "Player" SET "price" = 5.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'SN' LIMIT 1) AND "name" = 'Пате Сісс';
UPDATE "Player" SET "price" = 8.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'SN' LIMIT 1) AND "name" = 'Хабіб Діарра';
UPDATE "Player" SET "price" = 8.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'SN' LIMIT 1) AND "name" = 'Ассан Діао';
UPDATE "Player" SET "price" = 5.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'SN' LIMIT 1) AND "name" = 'Бамба Дьєн';
UPDATE "Player" SET "price" = 8.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'SN' LIMIT 1) AND "name" = 'Ібрагім Мбає';
UPDATE "Player" SET "price" = 9.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'SN' LIMIT 1) AND "name" = 'Іліман Ндіає';
UPDATE "Player" SET "price" = 8.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'SN' LIMIT 1) AND "name" = 'Ісмаїла Сарр';
UPDATE "Player" SET "price" = 10.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'SN' LIMIT 1) AND "name" = 'Ніколя Джексон';
UPDATE "Player" SET "price" = 8.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'SN' LIMIT 1) AND "name" = 'Садіо Мане';
UPDATE "Player" SET "price" = 6.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'SN' LIMIT 1) AND "name" = 'Шериф Ндіає';
UPDATE "Player" SET "price" = 5.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'TR' LIMIT 1) AND "name" = 'Алтай Байндир';
UPDATE "Player" SET "price" = 4.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'TR' LIMIT 1) AND "name" = 'Мерт Гюнок';
UPDATE "Player" SET "price" = 6.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'TR' LIMIT 1) AND "name" = 'Угурджан Чакир';
UPDATE "Player" SET "price" = 5.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'TR' LIMIT 1) AND "name" = 'Абдулкерім Бардакджи';
UPDATE "Player" SET "price" = 5.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'TR' LIMIT 1) AND "name" = 'Ерен Елмали';
UPDATE "Player" SET "price" = 6.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'TR' LIMIT 1) AND "name" = 'Зекі Челік';
UPDATE "Player" SET "price" = 6.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'TR' LIMIT 1) AND "name" = 'Меріх Демірал';
UPDATE "Player" SET "price" = 5.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'TR' LIMIT 1) AND "name" = 'Мерт Мюльдюр';
UPDATE "Player" SET "price" = 6.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'TR' LIMIT 1) AND "name" = 'Озан Кабак';
UPDATE "Player" SET "price" = 4.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'TR' LIMIT 1) AND "name" = 'Самет Акайдин';
UPDATE "Player" SET "price" = 6.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'TR' LIMIT 1) AND "name" = 'Ферді Кадіоглу';
UPDATE "Player" SET "price" = 5.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'TR' LIMIT 1) AND "name" = 'Чаглар Сьоюнджю';
UPDATE "Player" SET "price" = 7.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'TR' LIMIT 1) AND "name" = 'Ісмаїл Юксек';
UPDATE "Player" SET "price" = 5.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'TR' LIMIT 1) AND "name" = 'Каан Айхан';
UPDATE "Player" SET "price" = 8.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'TR' LIMIT 1) AND "name" = 'Оркун Кьокчю';
UPDATE "Player" SET "price" = 5.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'TR' LIMIT 1) AND "name" = 'Саліх Озджан';
UPDATE "Player" SET "price" = 8.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'TR' LIMIT 1) AND "name" = 'Хакан Чалханоглу';
UPDATE "Player" SET "price" = 11.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'TR' LIMIT 1) AND "name" = 'Арда Гюлер';
UPDATE "Player" SET "price" = 8.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'TR' LIMIT 1) AND "name" = 'Бариш Алпер Їлмаз';
UPDATE "Player" SET "price" = 6.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'TR' LIMIT 1) AND "name" = 'Деніз Гюль';
UPDATE "Player" SET "price" = 9.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'TR' LIMIT 1) AND "name" = 'Джан Узун';
UPDATE "Player" SET "price" = 6.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'TR' LIMIT 1) AND "name" = 'Ірфан Джан Кахведжі';
UPDATE "Player" SET "price" = 10.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'TR' LIMIT 1) AND "name" = 'Кенан Їлдиз';
UPDATE "Player" SET "price" = 8.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'TR' LIMIT 1) AND "name" = 'Керем Актюркоглу';
UPDATE "Player" SET "price" = 6.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'TR' LIMIT 1) AND "name" = 'Огуз Айдин';
UPDATE "Player" SET "price" = 7.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'TR' LIMIT 1) AND "name" = 'Юнус Акгюн';
UPDATE "Player" SET "price" = 4.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'UZ' LIMIT 1) AND "name" = 'Абдувохід Нематов';
UPDATE "Player" SET "price" = 4.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'UZ' LIMIT 1) AND "name" = 'Ботіралі Ергашев';
UPDATE "Player" SET "price" = 4.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'UZ' LIMIT 1) AND "name" = 'Уткір Юсупов';
UPDATE "Player" SET "price" = 6.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'UZ' LIMIT 1) AND "name" = 'Абдукодір Хусанов';
UPDATE "Player" SET "price" = 4.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'UZ' LIMIT 1) AND "name" = 'Абдулла Абдуллаев';
UPDATE "Player" SET "price" = 4.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'UZ' LIMIT 1) AND "name" = 'Авазбек Улмасаліев';
UPDATE "Player" SET "price" = 4.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'UZ' LIMIT 1) AND "name" = 'Бехруз Карімов';
UPDATE "Player" SET "price" = 4.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'UZ' LIMIT 1) AND "name" = 'Джахонгір Урозов';
UPDATE "Player" SET "price" = 4.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'UZ' LIMIT 1) AND "name" = 'Рустам Ашурматов';
UPDATE "Player" SET "price" = 4.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'UZ' LIMIT 1) AND "name" = 'Умар Ешмуродов';
UPDATE "Player" SET "price" = 4.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'UZ' LIMIT 1) AND "name" = 'Фаррух Сайфіев';
UPDATE "Player" SET "price" = 4.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'UZ' LIMIT 1) AND "name" = 'Ходжіакбар Аліджонов';
UPDATE "Player" SET "price" = 4.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'UZ' LIMIT 1) AND "name" = 'Шерзод Насруллаев';
UPDATE "Player" SET "price" = 6.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'UZ' LIMIT 1) AND "name" = 'Аббосбек Файзуллаев';
UPDATE "Player" SET "price" = 5.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'UZ' LIMIT 1) AND "name" = 'Азізжон Ганіев';
UPDATE "Player" SET "price" = 4.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'UZ' LIMIT 1) AND "name" = 'Акмал Мозговой';
UPDATE "Player" SET "price" = 4.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'UZ' LIMIT 1) AND "name" = 'Джамшид Іскандеров';
UPDATE "Player" SET "price" = 4.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'UZ' LIMIT 1) AND "name" = 'Достонбек Хамдамов';
UPDATE "Player" SET "price" = 5.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'UZ' LIMIT 1) AND "name" = 'Жалоліддін Машаріпов';
UPDATE "Player" SET "price" = 4.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'UZ' LIMIT 1) AND "name" = 'Оділжон Хамробеков';
UPDATE "Player" SET "price" = 5.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'UZ' LIMIT 1) AND "name" = 'Остон Урунов';
UPDATE "Player" SET "price" = 5.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'UZ' LIMIT 1) AND "name" = 'Отабек Шукуров';
UPDATE "Player" SET "price" = 4.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'UZ' LIMIT 1) AND "name" = 'Шерзод Есанов';
UPDATE "Player" SET "price" = 4.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'UZ' LIMIT 1) AND "name" = 'Азізбек Амонов';
UPDATE "Player" SET "price" = 6.5 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'UZ' LIMIT 1) AND "name" = 'Елдор Шомуродов';
UPDATE "Player" SET "price" = 5.0 WHERE "nationalTeamId" = (SELECT "id" FROM "NationalTeam" WHERE "code" = 'UZ' LIMIT 1) AND "name" = 'Ігор Сергеев';
COMMIT;
